import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React, {useState, useEffect} from "react";
import axios from "axios";
import Movie from "../comps/Movie";

const keyAPI = process.env.NEXT_PUBLIC_API_KEY;
const FEATURED_API = `https://api.themoviedb.org/3/discover/movie?sort_by=popularity.desc&api_key=${keyAPI}&page=1`;
const searchAPI = `https://api.themoviedb.org/3/search/movie?&api_key=${keyAPI}&query=`;

export default function Home() {
const [movieName, setMovieName] = useState([]);
const [searchTerm, setSearchTerm] = useState('');

//fetch version - .results is the variable used by the API
  // const getMovies = (API) => {
  //   fetch(API)
  //   .then((res) => res.json())
  //   .then((data) => {
  //     console.log(data);
  //     console.log(keyAPI);
  //     setMovieName(data.results);
  //   });
  // }

  const getMovies = (API) => {
    axios.get(API)
    .then(res => setMovieName(res.data.results))
    .catch(error => console.log(error))
  }

  useEffect(() => {
    getMovies(FEATURED_API)
  }, []);

  const handleOnSubmit = (e) => {
    e.preventDefault();
    if (searchTerm) 
    {
    getMovies(searchAPI+searchTerm);
    setSearchTerm('');
    }
  };

  const handleOnChange = (e) => {
    e.preventDefault();
    setSearchTerm(e.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Movies Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.headSearch}>
        <header>
          <form onSubmit={handleOnSubmit}>
            <input className={styles.search} type="search" placeholder="Search..." value={searchTerm} onChange={handleOnChange}/>
          </form>
        </header>
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Movies Data
        </h1>
        <h3>Get info about any movie!</h3>
      </main>
      
      <div className={styles.movieContainer}>
        {movieName.length > 0 && movieName.map((movie) => <Movie key={movie.id} {...movie} />)}
      </div>

    </div>
  )
}